# for local development
version: '3.9'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: matheushenrique35/app-financas-front
    container_name: app-financas-front
    environment:
      - URL_API=https://192.168.100.3:7171/api/
    ports:
      - '9070:80'
