# for local development
version: '3.9'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    image: matheushenrique35/app-financas-front
    container_name: app-financas-front
    ports:
      - '9070:80'
